### ISSUE TITLE
Homeassistant Update 2024.12.4 fails due to gardena-smart-system

### ISSUE THREAD

**Issue by tomatenkopp** [py-smart-gardena/hass-gardena-smart-system#234]
The recent update to 2024.12.4 fails, obviously due to an error in gardena-smart-systemintegration.
As a result, Homeassistant does a proper rollback to 2024.12.3

last entry in home-assistant-rollback.log before doing the rollback:
....
RuntimeError: Detected that custom integration 'gardena_smart_system' calls hass.async_create_task from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassasync_create_task at custom_components/gardena_smart_system/__init__.py, line 65: hass.bus.async_listen_once(EVENT_HOMEASSISTANT_STOP, lambda event: hass.async_create_task(gardena_system.stop())). Please report it to the author of the 'gardena_smart_system' custom integration
2024-12-18 11:15:13.716 WARNING (MainThread) [py.warnings] /usr/src/homeassistant/homeassistant/core.py:1015: RuntimeWarning: coroutine 'GardenaSmartSystem.stop' was never awaited
  while tasks := [

2024-12-18 11:15:19.575 WARNING (MainThread) [homeassistant.runner] Task could not be canceled and was still running after shutdown: <Task cancelling name='Task-209' coro=<SmartSystem.start_ws() running at /usr/local/lib/python3.13/site-packages/gardena/smart_system.py:198> wait_for=<Future pending cb=[Task.task_wakeup()]>>

**Comment by oliskippy** [comment]
The update worked on my side but probably because I was not connected to the Gardena service. This is my new issue, after good connexions for months, no chance anymore since beginning of December. I tried to reconnect after updating the keys, etc. No chance.
The integration became useless. 

`Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 17:50:48 (1 occurrences)
Last logged: 17:50:48

Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/gardena/smart_system.py", line 141, in __call_smart_system_get
    if self.__response_has_errors(response):
       ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/gardena/smart_system.py", line 131, in __response_has_errors
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '429 ' for url 'https://api.smart.gardena.dev/v1/locations'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/gardena_smart_system/__init__.py", line 49, in async_setup_entry
    await gardena_system.start()
  File "/config/custom_components/gardena_smart_system/__init__.py", line 87, in start
    await self.smart_system.update_locations()
  File "/usr/local/lib/python3.13/site-packages/gardena/smart_system.py", line 146, in update_locations
    response_data = await self.__call_smart_system_get(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        f"{self.SMART_HOST}/v1/locations"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/backoff/_async.py", line 183, in retry
    await asyncio.sleep(seconds)
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 718, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError: Global task timeout`

**Comment by ddrachau** [comment]
Slightly different error but the integration is not compatible with 2014.12.5 anymore

ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'gardena_smart_system': Unable to import component: No module named 'gardena'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/gardena_smart_system/__init__.py", line 5, in <module>
    from gardena.exceptions.authentication_exception import AuthenticationException
ModuleNotFoundError: No module named 'gardena'

**Comment by grm** [comment]
Hello,

By having a quick look into you errors, I am not sure they are related.
I am currently running the 2024.12.5 hass version in a test environement, and home assistant is starting. Does it starts on your side ? Or is it just the integration not starting ?

I had a quick look into it (and try to have more time in the next few days :) ), updated the underlying library to have latest versions, and will try to reproduce the issue on my side.

**Comment by grm** [comment]
Also, which version are you using ?

**Comment by ddrachau** [comment]
[hass-gardena-smart-system](https://github.com/py-smart-gardena/hass-gardena-smart-system) 1.1.0 with HASS 2024.12.5

**Comment by tomatenkopp** [comment]
1.1.1 on HASS 2024.1.5
Interestingly, I can enable the integration after HASS is started and everything seems to work fine.
But I don't dare leave it enabled in the live system and I don't have a test system available at the moment.

**Comment by ddrachau** [comment]
I created a separate test environment from the scratch running ghcr.io/home-assistant/home-assistant:2024.12.5 with only the gardena add found in HACS 1.1.1

I can download it and restarted HASS without a problem. But once I try to add the integration at devices I get the following error codes:

UI:
`Error
Config flow could not be loaded: {"message":"Invalid handler specified"}`

Code:
`[homeassistant.config_entries] Error occurred loading flow for integration gardena_smart_system: No module named 'gardena' `

**Comment by ddrachau** [comment]
Ok the problem seems to be related to the docker image of HASS. It changed the way HACS addons and/or their dependencies are searched for. Here you can find a workaround - https://github.com/home-assistant/core/issues/127966

**Comment by grm** [comment]
Thanks for the links @ddrachau ! 
It seems indeed there was an issue with this version 2024.12.5 ! Using the 2025.1 should solve it. Can you confirm this ?

**Comment by matteocorti** [comment]
I still see the log entries with 2025.2

```
2025-02-17 21:54:16.219 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 65, in <lambda>
    hass.bus.async_listen_once(EVENT_HOMEASSISTANT_STOP, lambda event: hass.async_create_task(gardena_system.stop()))
                                                                       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 809, in async_create_task
    frame.report_non_thread_safe_operation("hass.async_create_task")
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 368, in report_non_thread_safe_operation
    report(
    ~~~~~~^
        f"calls {what} from a thread other than the event loop, "
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        error_if_integration=True,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 164, in report
    report_usage(
    ~~~~~~~~~~~~^
        what,
        ^^^^^
    ...<4 lines>...
        level=level,
        ^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 242, in report_usage
    _report_integration_frame(
    ~~~~~~~~~~~~~~~~~~~~~~~~~^
        what,
        ^^^^^
    ...<3 lines>...
        integration_behavior is ReportBehavior.ERROR,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 340, in _report_integration_frame
    raise RuntimeError(
    ...<5 lines>...
    )
RuntimeError: Detected that custom integration 'gardena_smart_system' calls hass.async_create_task from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#hassasync_create_task at custom_components/gardena_smart_system/__init__.py, line 65: hass.bus.async_listen_once(EVENT_HOMEASSISTANT_STOP, lambda event: hass.async_create_task(gardena_system.stop())). Please report it to the author of the 'gardena_smart_system' custom integration
  while tasks := [
```

After that the core restarts by itself

**Comment by grm** [comment]
Fixed?
