### ISSUE TITLE
Getting "not all required fields are filled in" when trying to set it up

### ISSUE THREAD

**Issue by robsterst** [py-smart-gardena/hass-gardena-smart-system#37]
Hey guys,
thanks for the effort getting this into Hacs! 

I am trying to switch to this integration, coming from a custom Gardena integration. When trying to get it to work I get the error (see attached screenshot). Obviously all fields are filled when hitting "submit".

Any ideas? Running on Home assistant 0.111.4

Thanks!
<img width="180" alt="image" src="https://user-images.githubusercontent.com/51903185/88434169-e9239800-cdff-11ea-97ac-7aa98764aa28.png">

**Comment by dbrouwer1979** [comment]
I'm trying to setup this integration also. When I hit submit all field go blank and get the same message as robsterst mentioned above.
How to resolve?

**Comment by grm** [comment]
Strange issue,

I just released a new version and i do not have the same issue.
Which version of home assistant/hacs are you using ?
And which gardena system version ?

Thx,
Jérémie

**Comment by robsterst** [comment]
Just updated to latest Gardena integration I hacs. No change. 

Hass: 111.4
Hacs: 1.2.2
Gardena: 11319-2

**Comment by robsterst** [comment]
Is there anything I can do to get it to work? Updated versions so:

Hass: 114.1
Hacs: 1.3.3
Gardena:  11319-2

Still the same issue.

Thanks!
Rob

**Comment by grm** [comment]
Hello,

Can you take.a screenshot of the whole window ?
What fields do you fill ?

All fields must be filled (email/password and application key)

Jérémie

**Comment by jutgren** [comment]
Hello, 
I tried again to ad the intergration. 
![image](https://user-images.githubusercontent.com/68185647/95557149-a9d71180-0a14-11eb-8599-690c5b162d15.png)

when i push Send, nothing happens and I get a clean input window again. 

Hass 115.6
HACS 1.6.0
Gardena 0.2.2

**Comment by mrmireaux** [comment]
Hi there!

Thanks for the integration in Home Assistant! 
I am also getting an empty diaolg when I try to set the integration up. After pressing the send button the fields in the dialog where cleared.

Home Assistant Version: 0.114.2
Gardena Smart System: 0.2.2

Thanks!

**Comment by weinbrand** [comment]
@mrmireaux @jutgren 
I assume you forgot this step on the husqvarna developer website:
"Click on "+Connect new API" and connect the Authentication API and the GARDENA smart system API."

At least that was the fault I did ;-)

**Comment by mrmireaux** [comment]
@weinbrand Thank you very much! Works like a charm now :)
