### ISSUE TITLE
Integration doesn't work

### ISSUE THREAD

**Issue by dueltschi** [py-smart-gardena/hass-gardena-smart-system#4]
very same issue as reported by Johnyyy85 in the older repo. Integration doesn't work.

HACS installation done.
Husqvarna Application created and API linked
HA rebooted several times
When adding integration using Application Key, nothing happens. 

Error message: 

Logger: custom_components.gardena_smart_system.config_flow
Source: custom_components/gardena_smart_system/config_flow.py:133 
Integration: Gardena Smart System (documentation) 
First occurred: 13:17:42 (2 occurrences) 
Last logged: 13:17:59

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 70, in async_step_user
    user_input[CONF_CLIENT_ID])
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 133, in try_connection
    smart_system.update_locations()
  File "/usr/local/lib/python3.7/site-packages/gardena/smart_system.py", line 157, in update_locations
    if len(response_data["data"]) < 1:
KeyError: 'data'

**Comment by osks** [comment]
Do you get any errors logged in the Home Assistant log?

**Comment by osks** [comment]
> very same issue as reported by Johnyyy85 in the older repo. Integration doesn't work.
> 
> HACS installation done.
> Husqvarna Application created and API linked
> HA rebooted several times
> When adding integration using Application Key, nothing happens.
> 
> Error message:
> 
> Logger: custom_components.gardena_smart_system.config_flow
> Source: custom_components/gardena_smart_system/config_flow.py:133
> Integration: Gardena Smart System (documentation)
> First occurred: 13:17:42 (2 occurrences)
> Last logged: 13:17:59
> 
> Unexpected exception
> Traceback (most recent call last):
> File "/config/custom_components/gardena_smart_system/config_flow.py", line 70, in async_step_user
> user_input[CONF_CLIENT_ID])
> File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
> result = self.fn(*self.args, **self.kwargs)
> File "/config/custom_components/gardena_smart_system/config_flow.py", line 133, in try_connection
> smart_system.update_locations()
> File "/usr/local/lib/python3.7/site-packages/gardena/smart_system.py", line 157, in update_locations
> if len(response_data["data"]) < 1:
> KeyError: 'data'

This is actually from a bug in py-smart-gardena2. Most likely there is an error logged in the Home Assistant log, which is the actual error from the Gardena API.

I've released a new version of py-smart-gardena 2 (0.7.4) where I handle that "data" isn't present in response_data.

And also updated the required version for this integration.

Could you update the integration and test again?

**Comment by dueltschi** [comment]
Hi Osks

Thanks a lot for the very quick turnaround. The new version works and I was able to successfully integrate the gardena smart system. It shows now in the HA integrations and I can rename it + set a few options like smart watering duration. 

That's great News! Thanks again for all the great work! I was waiting a long time for this integration. 

I do have the smart watering system only (no smart irigation, nor mover). What states and services are available for the smart watering system? I could not find any documentation 

Best

**Comment by Johnyyy85** [comment]
I still have the same problem :( I have updated to the latest version as mentioned above and restarted HASS but i still doesn't work

Logger: custom_components.gardena_smart_system.config_flow
Source: custom_components/gardena_smart_system/config_flow.py:133
Integration: Gardena Smart System (documentation)
First occurred: 19:29:24 (1 occurrences)
Last logged: 19:29:24

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 70, in async_step_user
    user_input[CONF_CLIENT_ID])
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 133, in try_connection
    smart_system.update_locations()
  File "/usr/local/lib/python3.7/site-packages/gardena/smart_system.py", line 157, in update_locations
    if len(response_data["data"]) < 1:
KeyError: 'data'

**Comment by grm** [comment]
Hey @Johnyyy85, we released a new version tonight. Could you try uninstall and reinstall it please ?

 (the new custom url for hacs is : https://github.com/py-smart-gardena/hass-gardena-smart-system)

And also, did you update the hacs custom URL ?

**Comment by Johnyyy85** [comment]
Thanks! it's working now!
